# Site settings
title:  jekyll-glossary_tooltip Live Demo
description: >-
  Demo of the erikw/jekyll-glossary_tooltip Jekyll plugin
baseurl: ""
url: "https://erikw.github.io/jekyll-glossary_tooltip"
github_username:  erikw

# Build settings
markdown: kramdown
theme: minima
#remote_theme: heiswayi/thinkspace


header_pages: [null] # Remove about.md menu time

exclude:
  - bin/
  - Rakefile
  - Gemfile*
  - README.md

plugins:
  - jekyll-feed
  - jekyll-glossary_tooltip
