# Site settings
title:  jekyll-glossary_tooltip Live Demo
email: jekyll@tester.com
description: >- # this means to ignore newlines until "baseurl:"
  Demo of the https://github.com/erikw/jekyll-glossary_tooltip Jekyll plugin
baseurl: ""
url: "https://erikw.github.io/jekyll-glossary_tooltip"
github_username:  erikw

# Build settings
markdown: kramdown
theme: minima
#remote_theme: heiswayi/thinkspace

exclude:
  - bin/
  - Rakefile
  - Gemfile*
  - README.md

plugins:
  - jekyll-feed
  - jekyll-glossary_tooltip
