# This file was generated by Appraisal

source "https://rubygems.org"

gem "jekyll", "~> 4.0"

group :development, :test do
  gem "rake", "~> 13.0", require: false
  gem "travis", "~> 1.0", require: false
  gem "appraisal", "~> 2.4", require: false
end

group :test do
  gem "rspec", "~> 3.0"
  gem "rubocop", "~> 1.18", require: false
  gem "rubocop-rake", "~> 0.6", require: false
  gem "rubocop-rspec", "~> 2.4", require: false
  gem "simplecov", "~> 0.21"
end

gemspec path: "../"
