name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: main
  pull_request:
    branches: main

# OIDC permissions for qlty
permissions:
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [2.7.0, 3.0.1]
        gemfile:
          - gemfiles/jekyll_3.7.x.gemfile
          - gemfiles/jekyll_4.x.x.gemfile

    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          bundler: 2.2.18

      - name: Run tests
        run: bundle exec rake spec

      - name: Run linting
        run: bundle exec rake rubocop

      - name: Publish code coverage to qlty
        uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          format: simplecov
          files: coverage/.resultset.json
